# Generated by Django 2.2.5 on 2020-09-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Proprietário:')),
                ('doc_number', models.CharField(max_length=18, verbose_name='CPF / CNPJ:')),
                ('phone_number', models.IntegerField(verbose_name='Celular/Telefone:')),
                ('email', models.CharField(max_length=100, verbose_name='Nome Proprietario:')),
            ],
            options={
                'verbose_name': 'Lista de proprietário',
                'verbose_name_plural': 'Lista de proprietários',
                'ordering': ['name'],
            },
        ),
    ]
