# Generated by Django 2.2.5 on 2020-09-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Celular/Telefone:'),
        ),
    ]
