version: '3.7'

networks:
  mynetwork:
    driver: bridge

services:
  db:
    image: "postgres:12"
    environment: 
      - POSTGRES_DB=web
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
  
  web:
    build: .
    command: 
      sh -c "python /code/manage.py makemigrations && 
             python /code/manage.py migrate auth && 
             python /code/manage.py migrate --run-syncdb &&
             python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - db
    depends_on:
      - db
    environment: 
      - DB_HOST=db
      - DB_NAME=web
      - DB_USER=postgres
      - DB_PASSWORD=postgres

volumes:
  postgres_data: