# Generated by Django 2.2.5 on 2020-09-12 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=256, verbose_name='Tipo do Veículo:')),
                ('vehicle_model', models.CharField(max_length=256, verbose_name='Modelo do veículo:')),
                ('doc_number', models.CharField(max_length=256, verbose_name='Chassi do veículo:')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.Owner', verbose_name='Prosprietário:')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Lista de Veículos',
                'ordering': ['owner'],
            },
        ),
    ]
